### ISSUE TITLE
FEAT | Native feature in Kotlin

### ISSUE THREAD

**Issue by louisgv** [louisgv/mobile-challenge#20]
## 🚀 Feature Proposal

A Kotlin component that expand receipt on a modal seem simple enough for this last mile feature

**Comment by louisgv** [comment]
Using Fresco and PhotoView for Fresco to handle pinch zoom.

**Comment by louisgv** [comment]
Fresco is crashing app whenever  `setImageUri` is called. Below is the interaction flow:

1. Open app, press sign-in
2. Press the camera icon on the first item
3. Take picture with the bottom button, then accept the picture.
4. Once returned to expense list, long press the picture on the first item. This triggers the native module to run `popImage` from `com.pleolouis/popup/ImagePopupModule`, which open a blank PopupWindow
5. Press the gray area -> Crash

When tapping the gray view, the native module triggers             `draweeView.setImageURI("https://raw.githubusercontent.com/facebook/fresco/master/docs/static/logo.png", reactApplicationContext)`

Crash log: 
```
2019-11-19 16:42:44.303 7835-7937/com.pleolouis E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.pleolouis, PID: 7835
    java.lang.IllegalStateException
        at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:158)
        at com.facebook.drawee.components.DeferredReleaser.ensureOnUiThread(DeferredReleaser.java:100)
        at com.facebook.drawee.components.DeferredReleaser.cancelDeferredRelease(DeferredReleaser.java:95)
        at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:373)
        at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:266)
        at com.facebook.drawee.view.DraweeHolder.setController(DraweeHolder.java:198)
        at com.facebook.drawee.view.DraweeView.setController(DraweeView.java:131)
        at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:169)
        at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:180)
        at com.pleolouis.popup.ImagePopupModule$popImage$1.onViewTap(ImagePopupModule.kt:55)
        at me.relex.photodraweeview.DefaultOnDoubleTapListener.onSingleTapConfirmed(DefaultOnDoubleTapListener.java:42)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:323)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2019-11-19 16:42:44.321 7835-7937/com.pleolouis I/Process: Sending signal. PID: 7835 SIG: 9
```
